# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and release a new version to GitHub

name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2
      - name: Use Node.js 14.x
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v1
      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm install
      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: npm run build --if-present
      - name: Release
        if: steps.check.outputs.changed == 'true'
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.type }}
          release_name: Release ${{ steps.check.outputs.type }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: steps.check.outputs.changed == 'true'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./dist/locaties.user.js
          asset_name: locaties.user.js
          asset_content_type: text/javascript